Add method documentation to the README
scottbonline/sense pull request #33
Opened 2020-04-01 19:24 UTC by futzlarson

2020-04-01 19:53 UTC, Blackcell commented
+1

2020-04-01 21:20 UTC, kbickar requested changes
A little extra info needed

2020-04-01 21:20 UTC, kbickar commented on README.md
> +### Methods
Note these are the Synchronous methods

2020-04-01 21:20 UTC, kbickar commented on README.md
> +`authenticate(username, password)` | -
This must be called at the start of the session before anything else

2020-04-01 21:20 UTC, kbickar commented on README.md
> +`update_realtime()` | Update the realtime data.
Include that realtime data contains device on/off and power usage

2020-04-01 21:20 UTC, kbickar commented on README.md
> +`get_trend_data(scale)` | Fetches the trend data for a scale of time (e.g. day, month, year). It's mostly used when called by `update_trend_data()` which will get the trend data for all of the scales
update_trend_data() should get it's own line too and include that trend data would be total power usage for hour/day/month/year/etc

2020-05-22 17:41 UTC, futzlarson commented
I haven't used the tool yet, due to the documentation. I was trying to make it a little better. If you want to update my update, go for it.

2023-09-15 16:44 UTC, closed without merging